// <auto-generated />
namespace MalignantTumorSystem.Model.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.2-21211")]
    public sealed partial class add_MT_BC_OperativeTreatment : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_MT_BC_OperativeTreatment));
        
        string IMigrationMetadata.Id
        {
            get { return "201706220705169_add_MT_BC_OperativeTreatment"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
